--from pgAdmin import Departments from data\departments_cleaned.csv
--from pgAdmin import Dept_Emp from data\dept_emp.csv
--from pgAdmin import Dept_Mgr from data\dept_manager.csv
--from pgAdmin import Employees from data\employees.csv
--from pgAdmin import Salaries from data\salaries.csv
--from pgAdmin import Titles from data\titles.csv